### PR TITLE
Fix available roles issue #34

### PR DESCRIPTION
**Pull request by AmirKremer**

### CODE REVIEW

**Comment by neeckeloo** [comment]
I encountered the same issue.

**Comment by shaneog** [comment]
Is there something specific that is preventing this PR from being merged? @andytinycat

**Comment by andytinycat** [comment]
Nothing except my lack of time! I'll merge it now, and thank you for your patience.

**Comment by andytinycat** [comment]
Released 0.0.18 with this fix.

**Comment by shaneog** [comment]
Awesome, thank you

**Pull request merged**
