### PR TITLE
allow tag value delimiter to be configurable

### LINKED ISSUE #49: Allow custom tag value delimiter
Currently, tag values are delimited only by comma.
For example, if I have a server with the Roles tag set to web,db this server will have both roles.
If I use a different delimiter, ; for example, then the web;db will be treated as a single role.

I want to be able to set my delimiting factor as a configuration.
My use case is that I use knife-ec2 to spawn servers. When you pass tags to knife-ec2 they are comma delimited which makes it impossible to create tag values with commas in them, so I use ; as delimiter.

### PR DESCRIPTION
**Pull request by erez-rabih**
resolves #49

### CODE REVIEW

**Comment by gpeng** [comment]
Will this be getting merged? +1 from me... knife ec2 doesn't allow comma separated tags so this causes issues with chef provisioned servers. They already split their tags arg on commas for different tags.

**Comment by erez-rabih** [comment]
@gpeng In the meantime you can use this in your Gemfile:
```ruby
gem 'cap-ec2', require: false, git: "git@github.com:erez-rabih/cap-ec2.git", branch: "custom-delimiter"
```
I have been working this way for the past two months.

**Comment by gpeng** [comment]
@erez-rabih Thanks... I forked it from you for now. Hopefully it'll get merged :+1:

**Comment by kylev** [comment]
Rebase?

**Comment by dlahn** [comment]
Happy to merge this if it gets rebased @erez-rabih

**Comment by erez-rabih** [comment]
@dlahn I merged with master

**Pull request merged**
